name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: Update ${filename}
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.repositories, base.activity+community, isocalendar, music
          config_timezone: Australia/Sydney
          output_condition: skip-if-only-metadata-changed
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: half-year
          plugin_music: yes
          plugin_music_limit: 3
          plugin_music_mode: top
          plugin_music_time_range: short
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_user: .user.login
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          repositories_affiliations: ""        
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2
